from pydantic import BaseModel
from typing import List, Optional, Dict, Any
from datetime import datetime

# Input for Prediction
class PredictRequest(BaseModel):
    text: str  # Changed from 'String' to 'str'
    custom_labels: Optional[List[str]] = None 

# Input for adding a global label
class LabelCreate(BaseModel):
    label: str
    description: Optional[str] = None

# Input for Reporting a mistake
class FeedbackRequest(BaseModel):
    history_id: int
    correct_label: str

# Output structure for individual label results
class PredictionResult(BaseModel):
    label: str
    score: float

# Response for the prediction endpoint
class PredictResponse(BaseModel):
    history_id: int
    text: str
    top_results: List[PredictionResult]

# Response for history endpoint
class HistoryResponse(BaseModel):
    id: int
    query_text: str
    model_results: List[Dict[str, Any]]
    user_reported_wrong: bool
    correct_label_provided: Optional[str]
    timestamp: datetime

    class Config:
        orm_mode = True

# --- NEW ADDITIONS ---
class DescriptionSuggestionRequest(BaseModel):
    label: str
    description: str

class DescriptionSuggestionResponse(BaseModel):
    original: str
    suggested: str
    changes_note: str = "Generated by AI"


class LabelUpdate(BaseModel):
    label: str
    description: Optional[str] = None

class LabelResponse(BaseModel):
    id: int
    label: str
    description: Optional[str] = None
    is_active: bool

    class Config:
        orm_mode = True

class BulkPredictionResult(BaseModel):
    history_id: int
    text: str
    top_label: str
    confidence: float
    top_results: List[PredictionResult]

class BulkResponse(BaseModel):
    total_processed: int
    results: List[BulkPredictionResult]

class ExplainRequest(BaseModel):
    text: str
    label: str
    confidence: float

class ExplainResponse(BaseModel):
    text: str
    label: str
    explanation: str